rem call make clean -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_AARCH32
rem call make -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_AARCH32
rem call make clean -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_AARCH32
rem call make -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_AARCH32
rem call make clean -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_AARCH32
rem call make -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_AARCH32
rem call make clean -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_AARCH32
rem call make -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_AARCH32

rem call make clean -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_AARCH64
rem call make -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_AARCH64
rem call make clean -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_AARCH64
rem call make -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_AARCH64
rem call make clean -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_AARCH64
rem call make -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_AARCH64
rem call make clean -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_AARCH64
rem call make -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_AARCH64

rem call make clean -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_RISCV32
rem call make -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_RISCV32
rem call make clean -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_RISCV32
rem call make -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_RISCV32
rem call make clean -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_RISCV32
rem call make -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_RISCV32
rem call make clean -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_RISCV32
rem call make -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_RISCV32

call make clean -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_RISCV64 DEVICE=D1
call make -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_RISCV64 DEVICE=D1
call make clean -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_RISCV64 DEVICE=D1
call make -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_RISCV64 DEVICE=D1
call make clean -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_RISCV64 DEVICE=D1
call make -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_RISCV64 DEVICE=D1
call make clean -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_RISCV64 DEVICE=D1
call make -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_RISCV64 DEVICE=D1

rem call make clean -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
rem call make -f Makefile TARGET=0 DEBUG=0 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
rem call make clean -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
rem call make -f Makefile TARGET=0 DEBUG=1 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
rem call make clean -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
rem call make -f Makefile TARGET=1 DEBUG=0 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
rem call make clean -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
rem call make -f Makefile TARGET=1 DEBUG=1 ARCHITECTURE=ECO_AVR8 DEVICE=atmega328p
